### ISSUE TITLE
Issue API Keys

### ISSUE THREAD

**Issue by sarah-savage** [aspirepress/AspireCloud#1]
We need to be able to issue API keys to users of the project, to prevent abuse.

**Comment by chuckadams** [comment]
It's probably worth looking into Laravel Sanctum for this.  Hopefully it can stay out of the way when we need it to.  Otherwise maybe adapt https://github.com/ejarnutowski/laravel-api-key (which is unmaintained so we should just copy it rather than use it ootb)

**Comment by Tmeister** [comment]
Just thinking out loud here.

If we are going to issue API keys to users, we need a user system in place with all the standard requirements like:

* Register
* Login
* Password Recovery
* A single Dashboard
* A profile/setting page
* 2FA
* Session/Devices
* Etc.

As we are already using Laravel, I suggest starting with [Laravel Jetstream](https://jetstream.laravel.com/introduction.html). Jetstream already gives us a solid starting point with all the requirements listed above, and it uses [Laravel Sanctum](https://laravel.com/docs/11.x/sanctum) to handle the users' API keys and all the middleware.

Regarding the front end, we can choose between Livewire (Blade) or Inertia (React). I've worked with both on different projects.

That way, we can get a complete admin skeleton with a robust user system in a few days and I can take care of this.

What do you think? @sarah-savage @chuckadams

**Comment by chuckadams** [comment]
I'm good with using Jetstream, and I'd be much inclined to take the Inertia UI.
