### ISSUE TITLE
Condition text is not compatible with the MIT license

### ISSUE THREAD

**Issue by johnbillion** [aspirepress/AspireCloud#114]
Hi folks,

This project is MIT licensed but includes this statement in the readme file:

> It is free software, with the condition that it must not be used for commercial gain when distributing freely available products.

A statement like this is not compatible with the MIT. I am not a license expert, but I would recommend revisiting either the license or this text in the readme.

Cheers!

**Comment by chuckadams** [comment]
Yep, looks like a leftover from before we decided on a license.  Will go ahead and drop that phrase.
