### ISSUE TITLE
Capture and log all data coming from/going to instances through catchall

### ISSUE THREAD

**Issue by sarah-savage** [aspirepress/AspireCloud#19]
We want to capture all the data, including headers and body information, that is being passed in requests from WP instances to the .org endpoints, and the responses from .org coming back to the instances.

We need to set up a table with the following fields:

* request_type (GET, POST, etc.)
* request_headers (jsonb)
* request_body (jsonb)
* response_code (string/int)
* response_headers (jsonb)
* response_body (jsonb)

This data should be logged after the request is sent but BEFORE we send a response to the requester. 

Note that this data is NOT anonymized so we won't collect it forever. It's important that the plugin disclose we are logging this information so that users are not surprised.

**Comment by sarah-savage** [comment]
You'll need to submit a migration to aspirepress/aspirecloud-migrations and also submit the code to write this information here.

**Comment by chuckadams** [comment]
Implemented in #27
