### ISSUE TITLE
Implement endpoint: /plugins/info

### ISSUE THREAD

**Issue by chuckadams** [aspirepress/AspireCloud#56]

**Comment by Tmeister** [comment]
WIP in #69

**Comment by eadamsatx** [comment]
https://codex.wordpress.org/WordPress.org_API#Plugins

Similar to themes, the "action" query string branches this endpoint into 4 separate api contracts. Each have different expectations and return structures.

**Comment by chuckadams** [comment]
Implementation of the endpoint is here:
https://github.com/WordPress/wordpress.org/blob/95480bf69cbdd497844a73e2b2ef187f3c69c2d7/wordpress.org/public_html/wp-content/plugins/plugin-directory/standalone/class-plugins-info-api.php#L33

**Comment by chuckadams** [comment]
It looks to be three actions that are supported, with `hot_tags` being the only one we don't have.  Should be easy now that it's implemented for themes.  Also `popular_tags` is an alias for `hot_tags`, so four names, three actions.

**Comment by chuckadams** [comment]
I'm going to call this one implemented by #87 when it gets merged, and open a separate issue for version 1.0 and 1.1 support, which isn't going to be priority.
