### ISSUE TITLE
add caching

### ISSUE THREAD

**Issue by chuckadams** [aspirepress/AspireCloud#63]
We should make use of caching in Laravel as well as add HTTP caching headers.  This should be configured centrally, preferably in the api.php routes file.

**Comment by Tmeister** [comment]
@chuckadams 

For now, the caching is enabled by default, and the cache time is hardcoded.

Should those two options be a setting on the app level, add a couple of entries on the `.env` file, and use the config to change those values?

I think we should do that, but I'm wondering if this should be an opinionated setting or not.

**Comment by Tmeister** [comment]
Got it, 

As I read the following

> We should make use of caching in Laravel

I assumed to use the server-side caching.

I am working on the changes.

**Comment by chuckadams** [comment]
Being "opinionated" is fine, we can add a config file later as needed.  This was to get the foundations laid, we build on it as we go.  I'm calling this one implemented.
