### ISSUE TITLE
Write an endpoint to check for theme updatea

### ISSUE THREAD

**Issue by sarah-savage** [aspirepress/AspireCloud#7]
We need an endpoint to check for available theme updates.

**Comment by chuckadams** [comment]
Accidentally shadowed this with #42 and I'm going to keep The Answer as a valid ticket thanks 🙃

**Comment by chuckadams** [comment]
Doh, shouldn't have been closed as completed but it's also removed from the project and milestone so w/e

**Comment by yosefeliezrie** [comment]
@sarah-savage should this stay open or is #42 replacing it?
