### ISSUE TITLE
Add /download route that serves redirects to assets

### ISSUE THREAD

**Issue by chuckadams** [aspirepress/AspireCloud#94]
This route should be able to serve up at least theme/plugin .zip files as well as banners and screenshots.  If we have the asset hosted locally, it should redirect to our hosted version (e.g. a signed S3 url or a link to static content pushed to the CDN).  If the asset is not local, it should redirect to the upstream location then kick off a queued job to fetch the asset locally.  That is, we want this to be a write-behind cache.

Plugin and themes should have whichever relevant urls changed so that they point to /download instead of directly to upstream.

**Comment by Tmeister** [comment]
I have some questions here:

Does the [AspireSync](https://github.com/aspirepress/AspireSync) cover the initial download when the sync runs, or does that only get the metadata?

> If we have the asset hosted locally, it should redirect to our hosted version. If the asset is not local, it should redirect to the upstream location then kick off a queued 

Related to question #1, if the sync project gets those files, how do we know(from Cloud) where they are stored?

If we are going to handle the downloads and store files in the Cloud project, We can rely on Laravel's native Storage system (Local, S3).

Best,

**Comment by chuckadams** [comment]
AspireSync is still the way of mirroring both .org metadata and files, yes, and then AC is able to pick it up from sync.  Currently it's using a shared database to do this, but my latest changes to AC are removing that dependency, so I'll make some sort of export mechanism to do it that AC can import from (perhaps a .zip file of json files).

**Comment by Tmeister** [comment]
Hi @chuckadams 

I just want to be sure we are on the same page here. Please take the time to go through this and let me know what you think.

The URLs we are going to serve are: 

- Downloads `https://downloads.wordpress.org/plugin/elementor.3.25.4.zip`
- Screenshots `https://ps.w.org/elementor/assets/screenshot-1.gif?rev=3005087`
- Banners `https://ps.w.org/elementor/assets/banner-1544x500.png?rev=3164133`

The following diagram shows the logic (see below). If the assets are not on the local instance of `SC`, ' get them from upstream, create a job to get them and store them on the `SC` filesystem.

Question

1. Besides to store the files on the filesystem, either local or S3 ([Laravel Storages](https://laravel.com/docs/11.x/filesystem#driver-prerequisites)), we need to store the path somewhere, right? I think the answer is yes, and maybe we want to create a separate table just for these assets and map the original (upstream) URL with the local path for future reference, something like this:

| id | upstream_path | local_path |
|----|--------------|------------|
| 123e4567-e89b-12d3-a456-426614174000 | /plugin/plugin-slug.1.3.4.zip | plugins/path-to-secure-storage-file.zip |
| 123e4567-e89b-12d3-a456-426614174001 | plugin-slug/assets/banner-772x250.jpg | assets/banners/path-to-secure-storage-file.jpg |
| 123e4567-e89b-12d3-a456-426614174002 | /theme/linnet.1.0.15.zip | theme/path-to-secure-storage.zip |

What do you think?


### Diagram
```mermaid
sequenceDiagram
    participant Client
    participant AC as AspireCloud<br/>(L. App)
    participant Queue as Queue System<br/>(L. Queue/Jobs)
    participant S3 as S3/CDN<br/>(L. Storage)
    participant WP as WordPress.org

    Note over Queue: Uses Laravel Jobs<br/>DownloadAsset::dispatch()
    Note over S3: Uses Laravel Storage<br/>Storage::disk('s3')->put()
    
    Client->>AC: GET /download/{type}/{slug}
    
    alt Asset exists locally
        AC->>S3: Check if asset exists<br/>Storage::exists()
        S3-->>AC: Asset found
        AC->>Client: 302 Redirect to S3/CDN URL<br/>Storage::temporaryUrl()
    else Asset not found
        AC->>WP: Check if asset exists upstream
        WP-->>AC: Asset exists
        AC->>Client: 302 Redirect to WordPress.org
        AC->>Queue: Queue download job<br/>DownloadAsset::dispatch()
        Queue->>WP: Download asset<br/>Http::get()
        Queue->>S3: Store asset<br/>Storage::put()
    end
```

**Comment by chuckadams** [comment]
The interaction diagram looks about right, yes.  The table you're talking about should definitely become a thing.  AspireSync does have some overlapping functionality when it comes to tracking file assets, but it's not quite what we need here, and will probably get axed when we get this design off the ground.
